-- Cloudflare Workers caps Web Crypto PBKDF2 at 100,000 iterations.
-- Re-hash the initial accounts without storing their plaintext passwords.
UPDATE users SET password_hash = 'ZyxOCuKC83ME8e0ndRJHCQUWwu6cqtFTkfHt1IEMBQc', password_salt = 'jRA0znJoXIK2pBOsD9Sd9F784-fSf4WS', password_iterations = 100000, token_version = token_version + 1 WHERE username = 'admin';
UPDATE users SET password_hash = 'nh9K_DXYJ_MZBonMS4VEAONVhoIKqyOCl3VNW47XDPo', password_salt = 'j4QJUMDzCTTIqPZNxGvz_ncvOAdfhMKV', password_iterations = 100000, token_version = token_version + 1 WHERE username = 'aptis01';
UPDATE users SET password_hash = 'BHpjorUxWI_br45Jn8gowMuPgJRRzATu6gf7AL4xH9I', password_salt = 'GpAG1fTyr2PahyAc-Ksm0ncLFydPKtBl', password_iterations = 100000, token_version = token_version + 1 WHERE username = 'aptis02';
UPDATE users SET password_hash = 'ijOECxJ5W9OHn3rTXK5WBoCXPsi0agEBoUFiV-FiI6o', password_salt = 'kRw8CVz8hZa8fAJYKewS3d8RkP1THDnT', password_iterations = 100000, token_version = token_version + 1 WHERE username = 'aptis03';
UPDATE users SET password_hash = 'nmdx3zcs9boIwIlgIjmY2IgJCk9FMoSM04j2K60ggrg', password_salt = 'MU93Cje5B7V1Ujv3YuRlzNpMjqB4OA4A', password_iterations = 100000, token_version = token_version + 1 WHERE username = 'aptis04';
UPDATE users SET password_hash = 'j3vC85mwDTdlfc0_7LCDRxx6Qf60X1fe_5M_UQZLp0E', password_salt = 'G4bBdhLGJs08c4dPuDu52lMB4SnUFy-G', password_iterations = 100000, token_version = token_version + 1 WHERE username = 'aptis05';
UPDATE users SET password_hash = '4FDJl1WXG9_j5NKmwNl2N-FmzkBrLYfOOVfJZXj9Z_4', password_salt = 'Ow4uEub1Yy8SvhcaXCpc5k3Co9-_bC7D', password_iterations = 100000, token_version = token_version + 1 WHERE username = 'aptis06';
UPDATE users SET password_hash = 'lJuPPPbZP-thcxqqyJhKLqb4MSf572ncaX7nSmNe14s', password_salt = 'gMKtQT6Hf0mAXOVOg16Z7e-O-Rb--qEx', password_iterations = 100000, token_version = token_version + 1 WHERE username = 'aptis07';
UPDATE users SET password_hash = 'WaOah_UPobdHrpMZnnTvOwnDkbGEarcZR76KvmYsZlI', password_salt = 'OeAlEO5D5leh-sQgSNjwljLgmwNNcTZl', password_iterations = 100000, token_version = token_version + 1 WHERE username = 'aptis08';
UPDATE users SET password_hash = 'O9KXnQpuyH2MHZdAQ-RY15uJvLpycmQUkUYDjX-5Dqo', password_salt = 'umWSlxJ7GyWhLQiB_HVPysELbLlQV9Qw', password_iterations = 100000, token_version = token_version + 1 WHERE username = 'aptis09';
UPDATE users SET password_hash = 'hjRakkadaKYf15N0qnVuVeGV26Rcm-YIrQHnAFTQbDs', password_salt = 'y1fLMNqD2Qta2Li_BUyaS226dNUzn4-F', password_iterations = 100000, token_version = token_version + 1 WHERE username = 'aptis10';
UPDATE users SET password_hash = 'KXqxrUvTaTthYiPi2S3TXN-GlFX1EOp4XGV36BfuErs', password_salt = 'MusMdB0H-HvkY6SDx-GWrAL7k6MmkOuC', password_iterations = 100000, token_version = token_version + 1 WHERE username = 'aptis11';
UPDATE users SET password_hash = 'lLcxvt5IaZ1wNM7Ta-wxB0nAr7Grf8NJ9TBmXViaF1U', password_salt = 'mEvOMUgdzmSfbBHZGeO1kNxaYjFHd6sF', password_iterations = 100000, token_version = token_version + 1 WHERE username = 'aptis12';
UPDATE users SET password_hash = '6sEyL3vSHeV0TOZ42aCeYW6rbj__CRjCPD15112dJe0', password_salt = 'Aejl2n6aeucu9FmL8nnrEQtJSnixUYND', password_iterations = 100000, token_version = token_version + 1 WHERE username = 'aptis13';
UPDATE users SET password_hash = '1ToySP80M-oVLcn6Bx5r8BGYiMbPcpZEfkKyRVNR9uc', password_salt = 'tRHzFTEZ1J730fuIWLvtUGH9AGukKbrP', password_iterations = 100000, token_version = token_version + 1 WHERE username = 'aptis14';
UPDATE users SET password_hash = '5R3pkTWN6lBOI8idUGrleX8zkE_veW09mPfkrujotaI', password_salt = '-08s8NGKvozEl9qVGtdmlyigqrg_TmXt', password_iterations = 100000, token_version = token_version + 1 WHERE username = 'aptis15';
UPDATE users SET password_hash = 'guGdlg_T_AC0M0kl_CqTLb_SFsTwLy-tqJDVAo3Ffhk', password_salt = 'R5cXNZepBixGzFEYacOpRX6c59nw1M7G', password_iterations = 100000, token_version = token_version + 1 WHERE username = 'aptis16';
UPDATE users SET password_hash = '4eaa3mGihUAyLMxDTPF0_Fa7DbxXcB8MaXOl1nYJJKs', password_salt = 'pU-Te94kLVW5opwJaZwp1zqVesVIjyUh', password_iterations = 100000, token_version = token_version + 1 WHERE username = 'aptis17';
UPDATE users SET password_hash = 'P-aajZQKSYwa-OFfbEx5D9x09aYdIccjfFdGJgf8vsA', password_salt = 'Rir1DJgM_43FBmzvZGoAHyZEgDQ9Q-NZ', password_iterations = 100000, token_version = token_version + 1 WHERE username = 'aptis18';
UPDATE users SET password_hash = 'NQSfVtd1amzrkzjN1KxlhzvWjEEiFANS7NahsYeXQJE', password_salt = '2yT0zryCr_S7ZkcANPtypoEloyflTUWv', password_iterations = 100000, token_version = token_version + 1 WHERE username = 'aptis19';
UPDATE users SET password_hash = 'E7MeBGYSg1fHeRIQvzBMANJDsx23Atfe4Pb6V36lZBo', password_salt = '2wDIBZHc48K4Gd_WmGlfYiR2L-288q0k', password_iterations = 100000, token_version = token_version + 1 WHERE username = 'aptis20';
